### ISSUE TITLE
Laravel 10 error

### ISSUE THREAD

**Issue by alex-elivate** [suhasrkms/laravel-with-firebase-auth#4]
Hi, this works great in Laravel 8.  Do you have a trick to get this going on Laravel 10? I get an error **Unresolvable dependency resolving [Parameter #0 [ <required> string $projectId ]] in class Kreait\Firebase\Auth\ApiClient** When setting up the email only authentication download and updating Kreait\Firebase.

**Comment by suhasrkms** [comment]
Sure will bump it to v10 in few days.

**Comment by suhasrkms** [comment]
@alex-elivate the repo is updated to Laravel v10 refer #5
